### ISSUE TITLE
Cloud Functions Auth

### ISSUE THREAD

**Issue by blakecsharp** [docusign/connect-node-listener-gcloud#7]
Thank you for making this! 

I have a quick question regarding authentication. From my failures console on Docusign Connect, I am getting a 401 Unauthorized error (Error - The remote server returned an error: (401) Unauthorized.). I have tried different username / password combinations and opened my cloud function to be invoked by allUsers. However, I am still getting the error.

Do you have any suggestions? Am I missing something very obvious?

Thanks!

**Comment by LarryKlugerDS** [comment]
The listener uses DocuSign Connect's Basic Authentication feature. So you need to configure both the Connect configuration and the Google Cloud listener with the same name/password. 

See this video: https://www.youtube.com/watch?v=8bnE8Xroo1s

If you have more questions on this, open a support case via https://support.docusign.com/en/contactSupport
